var sampleChars = [
  {
    "pin": 0,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "10",

    "strength": "10",
    "dexterity": "10",
    "constitution": "10",
    "intelligence": "10",
    "wisdom": "10",
    "charisma": "10",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 1,
    "name": "",
    "title": "the Warrior",
    "level": "1",
    "hp": "13",

    "strength": "13",
    "dexterity": "10",
    "constitution": "13",
    "intelligence": "7",
    "wisdom": "8",
    "charisma": "9",
    "perception": "10",

    "wpn1name": "Broadsword",
    "wpn1desc": "A long, sharp, two-handed broadsword forged from steel. It was a gift from the leader of the army.",
    "wpn1type": "Large (d10)",
    "wpn2name": "Steel Shield",
    "wpn2desc": "A medium-sized, steel kite shield with their family crest painted on the front. It's dented and very old, but still sturdy.",
    "wpn2type": "Shield (AC +1)",
    "armorName": "Leather and Steel",
    "armorDesc": "Leather wrappings with steel plating over their joints and torso. On the front of their breastplate is the image of a lion, painted in gold.",
    "armorType": "Medium (AC 14)",
    "gear": "Carries a survival pack with basic camping gear, rations, a whetstone, a waterskin, a wooden bowl and spoon, and various small knives.",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "Dodge Roll",
    "perk1desc": "If an attack lands and there is room to move around, the Warrior can try to dodge the attack with a DEX check.",
    "perk2name": "Recovery Strike",
    "perk2desc": "If the Warrior makes an attack and it misses, they can use this move to roll the attack again.",
    "perk3name": "Fortify Defenses",
    "perk3desc": "Through endurance training, the Warrior has the ability to boost their defenses for 3 rounds, adding +1 to their AC.",
    "perk4name": "Cleaving Blow",
    "perk4desc": "When the Warrior has a sword equipped, they can cleave large objects in half or roll to attack, dealing 6d12 damage.",
    "perk5name": "Double Strike",
    "perk5desc": "The Warrior has mastered a combat technique that allows them to attempt a second attack if their first attack hits.",
    "perk6name": "Battlecry",
    "perk6desc": "With a shout, the Warrior can intimidate their enemies. This move gives a -1 to enemy attack rolls for 6 rounds.",
    "perk7name": "Shield Breaker",
    "perk7desc": "The Warrior can use this move to shatter an enemy's defenses if they fail a DC 18 DEX saving throw, causing -2 to the target's AC permanently.",
    "perk8name": "Killing Blow",
    "perk8desc": "Summoning their inner strength, the Warrior deals a lightning-fast strike, for 12d12 damage."
  },
  {
    "pin": 2,
    "name": "",
    "title": "the Cutpurse",
    "level": "1",
    "hp": "10",

    "strength": "8",
    "dexterity": "13",
    "constitution": "10",
    "intelligence": "10",
    "wisdom": "8",
    "charisma": "11",
    "perception": "10",

    "wpn1name": "Concealed Daggers",
    "wpn1desc": "A pair of concealed iron daggers that spring out into their hands from inside their sleeves. Excellent for sneak attacks. Roll 2 attacks if using both daggers.",
    "wpn1type": "Small (d4)",
    "wpn2name": "Poison Darts",
    "wpn2desc": "Small darts tipped with a poisonous powder. If the target fails a CON saving throw, they are poisoned and take 1d4 damage at the beginning of their turn for 3 rounds.",
    "wpn2type": "Ranged (d6)",
    "armorName": "Disappearing Cloak",
    "armorDesc": "A cloak as dark as the night, gives +1 on rolls for stealth-based DEX checks when it's dark, but provides little physical protection.",
    "armorType": "None (AC 10)",
    "gear": "Carries thieves' tools (lockpicks and bits of wire), rope, climbing gear, and empty sacks for storing larger loot.",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "Pickpocket",
    "perk1desc": "On a successful DC 12 DEX check, the Thief can steal a random item (decided on by the Game Master) from an NPC without them noticing.",
    "perk2name": "Smoke Bombs",
    "perk2desc": "The Thief throws down a small bomb that erupts into a cloud of smoke and dust, giving enemies disadvantage to attack rolls for 2 rounds.",
    "perk3name": "Vanish",
    "perk3desc": "The Thief vanishes from sight, remaining hidden for 3 rounds or until an enemy makes a successful DC14 perception check.",
    "perk4name": "Poisoned Blade",
    "perk4desc": "The Thief takes a turn to coat their blades in a deadly, fast-acting poison. Their next successful attack does 6d12 poison damage to their target.",
    "perk5name": "Keen Senses",
    "perk5desc": "The Thief can temporarily focus their senses, which gives them advantage on a perception check.",
    "perk6name": "Nimble Fingers",
    "perk6desc": "On a successful DC 17 DEX check, the Thief can steal a specific item from an NPC without them noticing.",
    "perk7name": "Skeleton Key",
    "perk7desc": "The Thief can pick any physical lock without needing to make a DEX check.",
    "perk8name": "Assassinate",
    "perk8desc": "If undetected, the Thief can strike an enemy for 12d12 damage and remain undetected by other enemies in the area."
  },
  {
    "pin": 3,
    "name": "",
    "title": "the Ice Mage",
    "level": "1",
    "hp": "10",

    "strength": "8",
    "dexterity": "8",
    "constitution": "10",
    "intelligence": "12",
    "wisdom": "12",
    "charisma": "10",
    "perception": "10",

    "wpn1name": "Polar Staff",
    "wpn1desc": "A cane-sized staff with a small globe made of solid ice at the top. It can cast the spell &#34;Freeze&#34; for an extra 1d4 of ice damage on a successful attack.",
    "wpn1type": "Medium (d8)",
    "wpn2name": "Owl Familiar",
    "wpn2desc": "A snowy owl companion, who can scout ahead form the skies and attack with it's sharp talons.",
    "wpn2type": "Ranged (d6)",
    "armorName": "Coat of Cold",
    "armorDesc": "A large, heavy, navy blue coat, decorated with emroidered snowflakes on the sleeves and tail. It's thick material is always slightly chilly and gives the wearer +1 AC against fire-based attacks.",
    "armorType": "Light (AC 12)",
    "gear": "Carries some old books, charts, and maps, a quill and ink set, a small telescope, and some basic survival equipment (cord, a lantern, a compass, knives).",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "Freeze Still Water",
    "perk1desc": "The Ice Mage freezes non-moving water or similar liquid in a 5ft square cube",
    "perk2name": "Ice Shard Shot",
    "perk2desc": "The Ice Mage fires 3 shards of hardened ice from thin air, rolling 3 ranged attacks and 1d6 damage for each shard.",
    "perk3name": "Blizzard",
    "perk3desc": "The Ice Mage creates a massive storm cloud with blistering winds that can freeze wet ground and create dangerous terrain.",
    "perk4name": "Summon Iceberg",
    "perk4desc": "The Ice Mage summons an iceberg from the sky that comes crashing down on a target for 6d12 damage.",
    "perk5name": "Freeze Raging Water",
    "perk5desc": "The Ice Mage freezes 50 cubic feet of fast-moving water instantly, which can freeze waves into spikes and create dangerous terrain.",
    "perk6name": "Summon Ice Golem",
    "perk6desc": "The Ice Mage summons a frozen golem made from blocks of ice (60 HP / 10 AC / 2d10 DMG) to fight and protect them for 6 rounds.",
    "perk7name": "Cold Blood",
    "perk7desc": "If target fails a DC 18 CON saving throw, this spell freezes their body solid and they are stuck in suspended animation for 7 rounds, or until they make a successful DC 18 STR saving throw.",
    "perk8name": "Summon Ice Dragon",
    "perk8desc": "The Ice Mage summons a massive white ice dragon that flies down from the sky to attack a target with it's teeth and claws for 12d12 damage."
  },
  {
    "pin": 4,
    "name": "",
    "title": "the Cleric",
    "level": "1",
    "hp": "12",

    "strength": "8",
    "dexterity": "7",
    "constitution": "11",
    "intelligence": "12",
    "wisdom": "12",
    "charisma": "10",
    "perception": "10",

    "wpn1name": "Ancient Tome",
    "wpn1desc": "A leather-bound book filled with words and illustrations depicting the Cleric's deity and its legacy. Allows the Cleric to call on their deity's power and heal a target for 1d8 hit points.",
    "wpn1type": "Small (d4)",
    "wpn2name": "Steel Buckler",
    "wpn2desc": "A solid shield made from wood and reinforced with steel, forming an odd symbol on the front. Used for protection but also can be used as a bashing weapon for 1d4 damage.",
    "wpn2type": "Shield (AC +1)",
    "armorName": "Blessed Garment",
    "armorDesc": "A long tunic over chainmail that shimmers even in darkness. -1 to stealth rolls, +2 to AC against regular creatures, and +4 AC against unholy creatures",
    "armorType": "Light (AC 12)",
    "gear": "Carries only a canteen and a strange-looking talisman.",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "Predict Danger",
    "perk1desc": "On a successful DC 12 INT check, the Cleric prays to their deity and can accurately predict the safer of two options.",
    "perk2name": "Healing Touch",
    "perk2desc": "The Cleric can lay hands on an ally and use their deity's powers to heal the ally for 3d8 HP.",
    "perk3name": "Shield Ally",
    "perk3desc": "The Cleric uses his shield to defend an ally, adding +1 to their AC for 3 rounds. If the ally moves away from them, the perk is cancelled.",
    "perk4name": "Commune with Deity",
    "perk4desc": "The Cleric makes a DC 15 WIS check and, if successful, can ask their deity (the Game Master) for a yes or no answer to a question.",
    "perk5name": "Truth Tongue",
    "perk5desc": "On a successful DC 16 WIS check, The Cleric casts a spell that forces a target to speak only the truth for 60 minutes.",
    "perk6name": "Circle of Healing",
    "perk6desc": "The Cleric casts a spell to heal all allies in a 5ft radius for 4d10 HP each.",
    "perk7name": "Divine Wrath",
    "perk7desc": "The Cleric summons forth their deity's divine wrath against a target, a burst of solar energy causing 10d12 light damage.",
    "perk8name": "Ressurection",
    "perk8desc": "This spell heals a single target for 12d12 HP or multiple targets for 6d12 each. It can also be used to grant an extra death saving throw to a character if they've failed all three."
  },
  {
    "pin": 5,
    "name": "",
    "title": "the Bard",
    "level": "1",
    "hp": "10",

    "strength": "11",
    "dexterity": "12",
    "constitution": "12",
    "intelligence": "8",
    "wisdom": "10",
    "charisma": "7",
    "perception": "10",

    "wpn1name": "Hunting Bow",
    "wpn1desc": "",
    "wpn1type": "Ranged (d6)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 6,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 7,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 8,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 9,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 10,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 11,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 12,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 13,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 14,
    "name": "",
    "title": "",
    "level": "1",
    "hp": "",

    "strength": "",
    "dexterity": "",
    "constitution": "",
    "intelligence": "",
    "wisdom": "",
    "charisma": "",
    "perception": "10",

    "wpn1name": "",
    "wpn1desc": "",
    "wpn1type": "Medium (d8)",
    "wpn2name": "",
    "wpn2desc": "",
    "wpn2type": "Ranged (d6)",
    "armorName": "",
    "armorDesc": "",
    "armorType": "None (AC 10)",
    "gear": "",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "",
    "perk1desc": "",
    "perk2name": "",
    "perk2desc": "",
    "perk3name": "",
    "perk3desc": "",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  },
  {
    "pin": 15,
    "name": "",
    "title": "the Cursed Beast",
    "level": "1",
    "hp": "12",

    "strength": "12",
    "dexterity": "10",
    "constitution": "12",
    "intelligence": "8",
    "wisdom": "10",
    "charisma": "7",
    "perception": "11",

    "wpn1name": "Beast Form",
    "wpn1desc": "Post-transformation, the Cursed Beast's body is a weapon itself with razor-sharp claws and a powerful, toothy maw.",
    "wpn1type": "Large (d10)",
    "wpn2name": "Iron Dagger",
    "wpn2desc": "A small, simple iron dagger. Sharp, but primarily used when transformation isn't an option.",
    "wpn2type": "Small (d4)",
    "armorName": "Beast Body",
    "armorDesc": "Transformed, the Cursed Beast's skin is thick and tough enough to withstand significant damage. When not in their Beast Form, the Cursed Beast's AC is 10.",
    "armorType": "Heavy (AC 16)",
    "gear": "The Cursed Beast carries only the dagger and a small sack of coins. His transformations are too frequent; carrying anything of value is a waste of time and energy.",

    "appearance": "",
    "personality": "",
    "backstory": "",

    "perk1name": "Cancel Transformation",
    "perk1desc": "After years of living with the curse, the Cursed Beast has learned how to cancel out of their Beast Form using a DC 12 WIS check.",
    "perk2name": "Forced Transformation",
    "perk2desc": "The Cursed Beast transforms beneath the full moon, but with a DC 13 WIS check they can transform into their beastly form with sheer willpower.",
    "perk3name": "Maintain Control",
    "perk3desc": "The Cursed Beast typically doesn't control their body when in Beast Form, but on a DC 14 WIS check they can wrestle control back for 3 rounds.",
    "perk4name": "",
    "perk4desc": "",
    "perk5name": "",
    "perk5desc": "",
    "perk6name": "",
    "perk6desc": "",
    "perk7name": "",
    "perk7desc": "",
    "perk8name": "",
    "perk8desc": ""
  }
];

var sampleQuests = [
  {
    "pin": 0,
    "questName": "",

    "settingsList": "",
    "npcList": "",
    "setup": "",

    "goal": "",
    "wander": "",

    "funFight": "",
    "twist": "",

    "challenge": "",
    "searchEnd": "",

    "climax": "",
    "epilogue": "",
    "cliffhanger": ""
  },
  {
    "pin": 1,
    "questName": "Bird Bones",

    "settingsList": "",
    "npcList": "",
    "setup": "",

    "goal": "",
    "wander": "",

    "funFight": "",
    "twist": "",

    "challenge": "",
    "searchEnd": "",

    "climax": "",
    "epilogue": "",
    "cliffhanger": ""
  },
  {
    "pin": 2,
    "questName": "",

    "settingsList": "",
    "npcList": "",
    "setup": "",

    "goal": "",
    "wander": "",

    "funFight": "",
    "twist": "",

    "challenge": "",
    "searchEnd": "",

    "climax": "",
    "epilogue": "",
    "cliffhanger": ""
  },
  {
    "pin": 3,
    "questName": "",

    "settingsList": "",
    "npcList": "",
    "setup": "",

    "goal": "",
    "wander": "",

    "funFight": "",
    "twist": "",

    "challenge": "",
    "searchEnd": "",

    "climax": "",
    "epilogue": "",
    "cliffhanger": ""
  },
  {
    "pin": 4,
    "questName": "",

    "settingsList": "",
    "npcList": "",
    "setup": "",

    "goal": "",
    "wander": "",

    "funFight": "",
    "twist": "",

    "challenge": "",
    "searchEnd": "",

    "climax": "",
    "epilogue": "",
    "cliffhanger": ""
  },
  {
    "pin": 5,
    "questName": "",

    "settingsList": "",
    "npcList": "",
    "setup": "",

    "goal": "",
    "wander": "",

    "funFight": "",
    "twist": "",

    "challenge": "",
    "searchEnd": "",

    "climax": "",
    "epilogue": "",
    "cliffhanger": ""
  },
  {
    "pin": 6,
    "questName": "",

    "settingsList": "",
    "npcList": "",
    "setup": "",

    "goal": "",
    "wander": "",

    "funFight": "",
    "twist": "",

    "challenge": "",
    "searchEnd": "",

    "climax": "",
    "epilogue": "",
    "cliffhanger": ""
  }
];
